server:
  port: 8081

spring:
  banner:
    location: banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${H2_USER}
    password: ${H2_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect